config/routes.rb
PullTracker::Application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :users
  resources :pulls
  resources :pull_lists
  resources :pull_manifests
end

app/models/pull_manifest.rb
class PullManifest < ActiveRecord::Base
  belongs_to :pull

  validates :pull_id, :file, presence: true
end

app/controllers/pull_manifests_controller.rb
class PullManifestsController < ApplicationController
  before_action :set_pull_manifest, only: [:show, :edit, :update, :destroy]

  # GET /pull_manifests
  # GET /pull_manifests.json
  def index
    @pull_manifests = PullManifest.all
  end

  # GET /pull_manifests/1
  # GET /pull_manifests/1.json
  def show
  end

  # GET /pull_manifests/new
  def new
    @pull_manifest = PullManifest.new
  end

  # GET /pull_manifests/1/edit
  def edit
  end

  # POST /pull_manifests
  # POST /pull_manifests.json
  def create
    @pull_manifest = PullManifest.new(pull_manifest_params)

    respond_to do |format|
      if @pull_manifest.save
        format.html { redirect_to @pull_manifest, notice: 'Pull manifest was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pull_manifest }
      else
        format.html { render action: 'new' }
        format.json { render json: @pull_manifest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pull_manifests/1
  # PATCH/PUT /pull_manifests/1.json
  def update
    respond_to do |format|
      if @pull_manifest.update(pull_manifest_params)
        format.html { redirect_to @pull_manifest, notice: 'Pull manifest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pull_manifest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pull_manifests/1
  # DELETE /pull_manifests/1.json
  def destroy
    @pull_manifest.destroy
    respond_to do |format|
      format.html { redirect_to pull_manifests_url, notice: 'Pull manifest was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pull_manifest
      @pull_manifest = PullManifest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pull_manifest_params
      params.require(:pull_manifest).permit(:pull_id, :file)
    end
end

app/views/pull_manifests/_form.html.haml
= simple_form_for(@pull_manifest) do |f|
  = f.error_notification

  .inputs
    = f.input :file
    = f.collection_select(:pull_id, Pull.all, :id, :name)

  .actions
    = f.button :submit

app/views/pull_manifests/edit.html.haml
= page_header 'Edit pull manifest', @pull_manifest.id

= render 'form'

= link_to 'Show', @pull_manifest
\|
= link_to 'Back', pull_manifests_path

app/views/pull_manifests/index.html.haml
= page_header 'Pull manifests'

%table.table.table-responsive.table-bordered.table-hover#pull_manifests-table
  %tr
    %th Pull ID
    %th File
    %th

  - @pull_manifests.each do |pull_manifest|
    %tr
      %td= link_to pull_manifest.pull.id, pull_path(pull_manifest.pull)
      %td= link_to pull_manifest.file, pull_manifest
      %td
        = link_to 'Edit', edit_pull_manifest_path(pull_manifest), class: 'btn btn-mini'
        = link_to 'Destroy', pull_manifest, method: :delete, confirm: 'Are you sure you want to delete this pull manifest?', class: 'btn btn-mini btn-danger'
%br

= link_to 'New Pull manifest', new_pull_manifest_path, class: 'btn btn-primary'

app/views/pull_manifests/new.html.haml
= page_header 'Create new pull manifest'

= render 'form'

= link_to 'Back', pull_manifests_path

app/views/pull_manifests/show.html.haml
= page_header @pull_manifest.id

#pull_manifest-detail
  %p
    %b= link_to @pull_manifest.pull.name, @pull_manifest.pull
  %p
    %b File:
    = @pull_manifest.file

= link_to 'Edit', edit_pull_manifest_path(@pull_manifest)
\|
= link_to 'Back', pull_manifests_path