config/routes.rb
PullTracker::Application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :users
  resources :pulls
  resources :pull_lists
  resources :pull_manifests
end

app/models/pull.rb
class Pull < ActiveRecord::Base
  has_many :pull_lists
  has_many :pull_manifests

  default_scope order('id DESC')

  validates :status, :description, :specimen_type, presence: true

  def name
    "Pull #{id}"
  end
end

app/controllers/pulls_controller.rb
class PullsController < ApplicationController
  before_action :set_pull, only: [:show, :edit, :update, :destroy]

  # GET /pulls
  # GET /pulls.json
  def index
    @pulls = Pull.all
  end

  # GET /pulls/1
  # GET /pulls/1.json
  def show
  end

  # GET /pulls/new
  def new
    @pull = Pull.new
  end

  # GET /pulls/1/edit
  def edit
  end

  # POST /pulls
  # POST /pulls.json
  def create
    @pull = Pull.new(pull_params)

    respond_to do |format|
      if @pull.save
        format.html { redirect_to @pull, notice: 'Pull was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pull }
      else
        format.html { render action: 'new' }
        format.json { render json: @pull.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pulls/1
  # PATCH/PUT /pulls/1.json
  def update
    respond_to do |format|
      if @pull.update(pull_params)
        format.html { redirect_to @pull, notice: 'Pull was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pull.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pulls/1
  # DELETE /pulls/1.json
  def destroy
    @pull.destroy
    respond_to do |format|
      format.html { redirect_to pulls_url, notice: 'Pull was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pull
      @pull = Pull.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pull_params
      params.require(:pull).permit(:description, :study, :participant_type, :visit_type, :specimen_type, :target_completion_date, :specimen_count, :scanned_count, :shipped_count, :not_found_count, :status, :hold, :repository_notes, :lab, :mta_number, :procedure)
    end
end

app/views/pulls/_form.html.haml
= simple_form_for(@pull) do |f|
  = f.error_notification

  .inputs
    = f.input :status
    = f.input :description
    = f.input :study
    = f.input :participant_type
    = f.input :visit_type
    = f.input :specimen_type
    = f.input :lab
    = f.input :procedure
    = f.input :hold
    = f.input :repository_notes
    = f.input :mta_number
    = f.input :specimen_count
    = f.input :not_found_count
    = f.input :scanned_count
    = f.input :shipped_count
    = f.input :target_completion_date

  .actions
    = f.button :submit

app/views/pulls/edit.html.haml
= page_header 'Edit pull', @pull.name

= render 'form'

= link_to 'Show', @pull
\|
= link_to 'Back', pulls_path

app/views/pulls/index.html.haml
= page_header 'Pulls'

%table.table.table-responsive.table-bordered.table-hover#pulls-table
  %tr
    %th ID
    %th Status
    %th Description
    %th Specimen type
    %th Study
    %th Participant type
    %th Visit type
    %th Lab
    %th Procedure
    %th Target completion date
    %th Hold
    %th Repository notes
    %th Total specimens requested
    %th Total scanned
    %th Total shipped
    %th Total not found
    %th

  - @pulls.each do |pull|
    %tr
      %td= link_to pull.id, pull_path(pull)
      %td= pull.status
      %td= pull.description
      %td= pull.specimen_type
      %td= pull.study
      %td= pull.participant_type
      %td= pull.visit_type
      %td= pull.lab
      %td= pull.procedure
      %td= pull.target_completion_date
      %td= pull.hold
      %td= pull.repository_notes
      %td= pull.specimen_count
      %td= pull.scanned_count
      %td= pull.shipped_count
      %td= pull.not_found_count
      %td
        = link_to 'Edit', edit_pull_path(pull), class: 'btn btn-mini'
        = link_to 'Destroy', pull, method: :delete, confirm: 'Are you sure you want to delete this pull?', class: 'btn btn-mini btn-danger'

%br

= link_to 'New Pull', new_pull_path, class: 'btn btn-primary'

app/views/pulls/new.html.haml
= page_header 'Create new pull'

= render 'form'

= link_to 'Back', pulls_path

app/views/pulls/show.html.haml
= page_header @pull.name

#pull-detail
  %p
    %b ID:
    =@pull.id
  %p
    %b Status:
    = @pull.status
  %p
    %b Description:
    = @pull.description
  %p
    %b Specimen type:
    = @pull.specimen_type
  %p
    %b Study:
    = @pull.study
  %p
    %b Participant type:
    = @pull.participant_type
  %p
    %b Visit type
    = @pull.visit_type
  %p
    %b Lab:
    = @pull.lab
  %p
    %b Procedure:
    = @pull.procedure
  %p
    %b Target completion date:
    = @pull.target_completion_date
  %p
    %b Hold:
    = @pull.hold
  %p
    %b Repository notes:
    = @pull.repository_notes
  %p
    %b Total specimens requested:
    = @pull.specimen_count
  %p
    %b Has Total scanned:
    = @pull.scanned_count
  %p
    %b Total shipped:
    = @pull.shipped_count
  %p
    %b Total not found:
    = @pull.not_found_count

  %p
    %b Pull lists:
  %ul
    - @pull.pull_lists.each do |pull_list|
      %li= link_to pull_list.file, pull_list

  %p
    %b Pull manifests:
  %ul
    - @pull.pull_manifests.each do |pull_manifest|
      %li= link_to pull_manifest.file, pull_manifest

= link_to 'Edit', edit_pull_path(@pull)
\|
= link_to 'Back', pulls_path