config/routes.rb
PullTracker::Application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :users
  resources :pulls
  resources :pull_lists
  resources :pull_manifests
end

app/views/layouts/_alerts.html.haml
- flash.each do |name, msg|
  %div{class: "alert alert-#{name == :notice ? 'success' : 'error'}"}
    %a.close{"data-dismiss" => "alert"} &#215;
    = content_tag :div, msg, id: "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_header.html.haml
%header#site-header
  .navbar.navbar-fixed-top
    .navbar-inner
      .container-fluid
        = link_to 'Pull tracker', root_path, class: 'brand'
        - if @current_user
          %button.btn.btn-navbar{'data-target' => '.nav-collapse', 'data-toggle' => 'collapse', 'type' => 'button'}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          .nav-collapse.collapse
            %ul.nav#site-nav
              %li
                = link_to 'Pulls', pulls_path
              %li
                = link_to 'Users', users_path
            %ul.pull-right.nav#user-nav
              %li.dropdown
                %a{'href' => '#', 'class' => 'dropdown-toggle', 'data-toggle' => 'dropdown'}
                  = @current_user.full_name
                  %b.caret
                %ul.dropdown-menu
                  %li
                    = link_to 'Edit profile', edit_user_path(@current_user)
                  %li.divider
                  %li
                    = link_to 'Sign out', destroy_user_session_path, method: 'DELETE'

app/views/layouts/_page_header.html.haml
- content_for :page_header do
  .row-fluid
    .span12
      %header#page-header.page-header
        %h1
          = h1
          - if small
            %small= small

app/views/layouts/_site_footer.html.haml
.row-fluid
  .span12
    %footer#site-footer.site-footer

app/views/layouts/_site_header.html.haml
%header#site-header.site-header
  .navbar.navbar-fixed-top
    .navbar-inner
      .container-fluid
        = link_to 'Home', root_path, class: 'brand'
        - if user_signed_in?
          %button.btn.btn-navbar{'data-target' => '.nav-collapse', 'data-toggle' => 'collapse', 'type' => 'button'}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          .nav-collapse.collapse
            %ul.nav#site-nav
              %li{class: ('active' if controller?('pulls'))}
                = link_to 'Pulls', pulls_path
              %li{class: ('active' if controller?('pull_lists'))}
                = link_to 'Pull lists', pull_lists_path
              %li{class: ('active' if controller?('pull_manifests'))}
                = link_to 'Pull manifests', pull_manifests_path
              %li{class: ('active' if controller?('users'))}
                = link_to 'Users', users_path

            %ul.pull-right.nav#user-nav
              %li.dropdown
                %a{'href' => '#', 'class' => 'dropdown-toggle', 'data-toggle' => 'dropdown'}
                  = current_user.full_name
                  %b.caret
                %ul.dropdown-menu
                  %li
                    = link_to 'Edit profile', edit_user_path(current_user)
                  %li.divider
                  %li
                    = link_to 'Sign out', destroy_user_session_path, method: 'DELETE'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= content_for?(:title) ? "Pull tracker: #{yield :title}" : "Pull tracker"
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = render 'layouts/site_header'

    .container-fluid
      %section{role: "main"}

        - if content_for?(:page_header)
          = yield :page_header

        .row-fluid
          - if content_for?(:sidebar)
            .span3
              .nav#page-nav#sidebar
                = yield :sidebar
          %div{class: "span#{content_for?(:sidebar) ? 9 : 12}"}
            #content
              = render 'layouts/alerts'
              = yield

      = render 'layouts/site_footer'